name: Create Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: anton-yurchenko/git-release@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
