name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        xcode-version: ['13.0']
        destination: ['platform=OS X', 'platform=iOS Simulator,OS=15.0,name=iPhone 12']

    steps:
      - uses: actions/checkout@v2

      - name: Set Xcode version to ${{ matrix.xcode-version }}
        run: xcversion select ${{ matrix.xcode-version }}

      - name: Run tests
        run: |
          set -o pipefail
          xcodebuild test -scheme HTTP-Package -destination '${{ matrix.destination }}' | bundle exec xcpretty -r html --output .build/reports/tests.html

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-report-${{ matrix.destination }}
          path: .build/reports/tests.html
